apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-sampleapp
  labels:
    app: demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: frontend-container
        image: devopsvconn/frontend-app:latest
        ports:
        - containerPort: 3000


